// languages.dart

class AppTranslations {
  static final Map<String, Map<String, String>> values = {
    'pt': {
      'startBtn': 'INICIAR',
      'welcomeMsg': 'Cuidado inteligente com a sua saúde.',
      'welcome': 'Bem-vindo de volta!',
      'subtitle': 'Faça login para acessar sua conta e falar com a Diana.',
      'sponsor': 'Patrocinado por Eurofarma',
      'signin': 'Entrar',
      'signup': 'Cadastrar',
      'userPlaceholder': 'E-mail',
      'namePlaceholder': 'Nome Completo',
      'passPlaceholder': 'Senha',
      'newHere': 'Novo por aqui?',
      'createAccount': 'Crie uma conta',
      'alreadyHaveAccount': 'Já tem uma conta?',
      'dianaTitle': 'Diana',
      'dianaSub': 'Assistente Virtual de Saúde Eurofarma',
      'dianaChatPlaceholder': 'Digite sua dúvida sobre rotina ou glicemia...',
      'medReminder': 'Meus Medicamentos',
      'addMed': 'Adicionar Remédio',
      'medName': 'Nome do Remédio',
      'medSchedule': 'Horários (ex: 08:00, 20:00)',
      'medStock': 'Estoque Atual (unidades)',
      'medDaily': 'Consumo Diário (unidades)',
      'save': 'Salvar',
      'stockSuffix': 'dias restantes. Hora de comprar!',
      'stockSafe': 'Estoque seguro para mais de',
      'days': 'dias.',
      'dianaGreeting': 'Olá! Sou a **Diana**, sua assistente de saúde Eurofarma. Como posso te ajudar a cuidar da sua rotina de glicemia hoje?',
      'errorAuth': 'Usuário ou senha incorretos.',
      'errorEmpty': 'Por favor, preencha todos os campos.',
      'successRegister': 'Conta criada com sucesso! Por favor, responda ao questionário de perfil.',
      'dianaThinking': 'Diana está digitando...',
      'notifTitle': 'Permitir Notificações?',
      'notifBody': 'O GlicoCare gostaria de enviar lembretes de medicamentos e alertas de estoque.',
      'allow': 'Permitir',
      'deny': 'Agora não',
      'chip1': '🍎 Alimentos indicados',
      'chip2': '💊 Dica de medicação',
      'chip3': '📊 O que fazer na hipoglicemia?',
      'profileTitle': 'Perfil do Usuário',
      'close': 'Fechar',
      'questionTitle': 'Questionário de Perfil',
      'q1': '1. Quando a sua glicemia sai do esperado, qual é a sua primeira reação?',
      'q1_a': 'Fico muito preocupado(a) e fico checando o tempo todo.',
      'q1_b': 'Fico irritado(a) e dá vontade de deixar para lá.',
      'q1_c': 'Encaro de forma objetiva e sigo o plano.',
      'q1_d': 'Me sinto perdido(a) e sem saber o que fazer.',
      'q2': '2. Como prefere lidar com momentos de estresse ou desafios?',
      'q2_a': 'Preciso de acolhimento e conversa calma.',
      'q2_b': 'Busco dados e explicações bem diretas.',
      'q2_c': 'Prefiro descontração para aliviar o peso.',
      'q2_d': 'Preciso de orientações passo a passo.',
      'q3': '3. Qual tom de conversa você mais detesta?',
      'q3_a': 'Tom de "bronca" ou professoral.',
      'q3_b': 'Falas muito longas e sem objetividade.',
      'q3_c': 'Falta de empatia ou frieza.',
      'q3_d': 'Termos muito complexos ou difíceis.',
      'q4': '4. Como quer que a Diana fale com você?',
      'q4_a': 'Acolhedora e calma (foco em tranquilizar).',
      'q4_b': 'Direta e objetiva (foco em dados e tópicos).',
      'q4_c': 'Motivadora e leve (foco em incentivo sem cobranças).',
      'q4_d': 'Educativa e detalhista (explicando o básico com paciência).',
      'q5': '5. Qual é a sua preferência sobre lembretes?',
      'q5_a': 'Avisos suaves e carinhosos.',
      'q5_b': 'Lembretes secos e diretos.',
      'q5_c': 'Avisos com toque de incentivo.',
      'q5_d': 'Lembretes explicativos do motivo da dose.',
      'q6': '6. Como é o seu ritmo de rotina no dia a dia?',
      'q6_a': 'Muito corrida, me causa ansiedade.',
      'q6_b': 'Estruturada e bem planejada.',
      'q6_c': 'Um pouco imprevisível e agitada.',
      'q6_d': 'Ainda estou tentando organizar minha rotina.',
      'q7': '7. Como você costuma se alimentar?',
      'q7_a': 'Sigo meu planejamento com disciplina.',
      'q7_b': 'Tenho ansiedade e acabo descontando na comida.',
      'q7_c': 'Às vezes me chateio por ter limitações na dieta.',
      'q7_d': 'Ainda não entendo bem a contagem de carboidratos.',
      'q8': '8. Qual seu nível de atividade física?',
      'q8_a': 'Pratico exercícios regularmente.',
      'q8_b': 'Tenho dificuldade de manter o ritmo por estresse.',
      'q8_c': 'Acho chato mas faço quando dá.',
      'q8_d': 'Estou começando agora.',
      'q9': '9. Qual seu maior desafio atual na saúde?',
      'q9_a': 'Manter a calma e não me estressar.',
      'q9_b': 'Não me frustrar com oscilações normais.',
      'q9_c': 'Lembrar dos remédios e estoque sem perder tempo.',
      'q9_d': 'Aprender tudo sobre o diabetes do zero.',
      'q10': '10. Há quanto tempo você lida com o diabetes?',
      'q10_a': 'Descobri há pouco tempo.',
      'q10_b': 'Há alguns anos e já conheço bem.',
      'q10_c': 'Há muito tempo, mas ainda fico apreensivo(a).',
      'q10_d': 'Há bastante tempo, mas tenho dias de raiva da rotina.',
    },
    'en': {
      'startBtn': 'START',
      'welcomeMsg': 'Smart care for your health.',
      'welcome': 'Welcome back!',
      'subtitle': 'Log in to access your account and talk to Diana.',
      'sponsor': 'Sponsored by Eurofarma',
      'signin': 'Sign In',
      'signup': 'Sign Up',
      'userPlaceholder': 'Email',
      'namePlaceholder': 'Full Name',
      'passPlaceholder': 'Password',
      'newHere': 'New here?',
      'createAccount': 'Create an account',
      'alreadyHaveAccount': 'Already have an account?',
      'dianaTitle': 'Diana',
      'dianaSub': 'Eurofarma Virtual Health Assistant',
      'dianaChatPlaceholder': 'Type your question about routine or blood sugar...',
      'medReminder': 'My Medications',
      'addMed': 'Add Medication',
      'medName': 'Medication Name',
      'medSchedule': 'Schedules (e.g., 08:00, 20:00)',
      'medStock': 'Current Stock (units)',
      'medDaily': 'Daily Consumption (units)',
      'save': 'Save',
      'stockSuffix': 'days remaining. Time to restock!',
      'stockSafe': 'Safe stock for more than',
      'days': 'days.',
      'dianaGreeting': 'Hello! I am **Diana**, your Eurofarma health assistant. How can I help you manage your blood sugar routine today?',
      'errorAuth': 'Incorrect email or password.',
      'errorEmpty': 'Please fill in all fields.',
      'successRegister': 'Account created successfully! Please complete the profile questionnaire.',
      'dianaThinking': 'Diana is typing...',
      'notifTitle': 'Allow Notifications?',
      'notifBody': 'GlicoCare would like to send medication reminders and stock alerts.',
      'allow': 'Allow',
      'deny': 'Not now',
      'chip1': '🍎 Recommended foods',
      'chip2': '💊 Medication tip',
      'chip3': '📊 What to do in hypoglycemia?',
      'profileTitle': 'User Profile',
      'close': 'Close',
      'questionTitle': 'Profile Questionnaire',
      'q1': '1. When your blood sugar goes out of target, what is your first reaction?',
      'q1_a': 'I get very worried and check it all the time.',
      'q1_b': 'I get annoyed and feel like ignoring it.',
      'q1_c': 'I handle it objectively and follow the plan.',
      'q1_d': 'I feel lost and unsure of what to do.',
      'q2': '2. How do you prefer to handle stressful moments or challenges?',
      'q2_a': 'I need comfort and a calm conversation.',
      'q2_b': 'I look for data and direct explanations.',
      'q2_c': 'I prefer lightness to relieve the burden.',
      'q2_d': 'I need step-by-step guidance.',
      'q3': '3. What tone of conversation do you dislike the most?',
      'q3_a': 'A scolding or lecturing tone.',
      'q3_b': 'Long speeches lacking objectivity.',
      'q3_c': 'Lack of empathy or coldness.',
      'q3_d': 'Overly complex or difficult terms.',
      'q4': '4. How would you like Diana to talk to you?',
      'q4_a': 'Welcoming and calm (focus on reassuring).',
      'q4_b': 'Direct and objective (focus on data and bullet points).',
      'q4_c': 'Encouraging and light (focus on motivation).',
      'q4_d': 'Educational and detailed (explaining the basics with patience).',
      'q5': '5. What is your preference for reminders?',
      'q5_a': 'Gentle and warm notices.',
      'q5_b': 'Short and direct reminders.',
      'q5_c': 'Reminders with an encouraging tone.',
      'q5_d': 'Explanatory reminders stating the reason for the dose.',
      'q6': '6. How is your daily routine pace?',
      'q6_a': 'Very rushed, causes me anxiety.',
      'q6_b': 'Structured and well-planned.',
      'q6_c': 'A bit unpredictable and busy.',
      'q6_d': 'I am still trying to organize my routine.',
      'q7': '7. How do you usually manage your diet?',
      'q7_a': 'I follow my plan with discipline.',
      'q7_b': 'I feel anxious and end up overeating.',
      'q7_c': 'Sometimes I get upset about dietary limits.',
      'q7_d': 'I still don\'t understand carb counting well.',
      'q8': '8. What is your physical activity level?',
      'q8_a': 'I exercise regularly.',
      'q8_b': 'I struggle to stay consistent due to stress.',
      'q8_c': 'I find it boring but do it when I can.',
      'q8_d': 'I am just starting out now.',
      'q9': '9. What is your biggest health challenge right now?',
      'q9_a': 'Staying calm and avoiding stress.',
      'q9_b': 'Not getting frustrated with normal fluctuations.',
      'q9_c': 'Remembering medications and stock without wasting time.',
      'q9_d': 'Learning everything about diabetes from scratch.',
      'q10': '10. How long have you been managing diabetes?',
      'q10_a': 'I was diagnosed recently.',
      'q10_b': 'For a few years and I know it well.',
      'q10_c': 'For a long time, but I still feel apprehensive.',
      'q10_d': 'For a long time, but I have days where I feel angry at the routine.',
    },
    'zh': {
      'startBtn': '开始',
      'welcomeMsg': '为您的健康提供智能护理。',
      'welcome': '欢迎回来！',
      'subtitle': '登录以访问您的帐户并与 Diana 交谈。',
      'sponsor': '由 Eurofarma 赞助',
      'signin': '登录',
      'signup': '注册',
      'userPlaceholder': '电子邮件',
      'namePlaceholder': '全名',
      'passPlaceholder': '密码',
      'newHere': '新用户？',
      'createAccount': '创建账户',
      'alreadyHaveAccount': '已有账户？',
      'dianaTitle': 'Diana',
      'dianaSub': 'Eurofarma 虚拟健康助手',
      'dianaChatPlaceholder': '输入您关于日常或血糖的问题...',
      'medReminder': '我的药物',
      'addMed': '添加药物',
      'medName': '药物名称',
      'medSchedule': '服用时间（例如：08:00、20:00）',
      'medStock': '当前库存（单位）',
      'medDaily': '每日用量（单位）',
      'save': '保存',
      'stockSuffix': '天剩余。该补充库存了！',
      'stockSafe': '安全库存可维持',
      'days': '天。',
      'dianaGreeting': '您好！我是 **Diana**，您的 Eurofarma 健康助手。今天我能如何帮助您管理血糖日常？',
      'errorAuth': '用户名或密码错误。',
      'errorEmpty': '请填写所有字段。',
      'successRegister': '账户创建成功！请回答个人资料问卷。',
      'dianaThinking': 'Diana 正在输入...',
      'notifTitle': '允许通知？',
      'notifBody': 'GlicoCare 希望发送用药提醒和库存警报。',
      'allow': '允许',
      'deny': '暂不',
      'chip1': '🍎 推荐食物',
      'chip2': '💊 用药提示',
      'chip3': '📊 低血糖怎么办？',
      'profileTitle': '个人资料',
      'close': '关闭',
      'questionTitle': '个人资料问卷',
      'q1': '1. 当血糖超出预期时，您的第一反应是什么？',
      'q1_a': '我非常担心，会不停地检查。',
      'q1_b': '我很烦躁，想置之不理。',
      'q1_c': '我客观对待并按照计划执行。',
      'q1_d': '我感到迷茫，不知所措。',
      'q2': '2. 您希望如何处理压力或挑战？',
      'q2_a': '我需要关怀和平静的对话。',
      'q2_b': '我寻求直接的数据和解释。',
      'q2_c': '我喜欢轻松的方式来减轻负担。',
      'q2_d': '我需要一步一步的指导。',
      'q3': '3. 您最不喜欢的对话语气是什么？',
      'q3_a': '责备或说教的语气。',
      'q3_b': '冗长且缺乏重点的发言。',
      'q3_c': '缺乏同理心或冷漠。',
      'q3_d': '过于复杂或困难的词汇。',
      'q4': '4. 您希望 Diana 如何与您沟通？',
      'q4_a': '温和冷静（侧重于安抚）。',
      'q4_b': '直接客观（侧重于数据和要点）。',
      'q4_c': '积极轻松（侧重于鼓励）。',
      'q4_d': '耐心细致（耐心地解释基础知识）。',
      'q5': '5. 您对提醒有何偏好？',
      'q5_a': '温和友好的提醒。',
      'q5_b': '简短直接的提醒。',
      'q5_c': '带有鼓励色彩的提醒。',
      'q5_d': '说明剂量理由的解释性提醒。',
      'q6': '6. 您日常生活的节奏如何？',
      'q6_a': '非常匆忙，会让我感到焦虑。',
      'q6_b': '有条不紊且规划良好。',
      'q6_c': '有点难以预测和忙碌。',
      'q6_d': '我仍在努力整理我的生活日常。',
      'q7': '7. 您平时如何安排饮食？',
      'q7_a': '我严格按照计划安排饮食。',
      'q7_b': '我感到焦虑，最终通过暴饮暴食泄愤。',
      'q7_c': '有时会对饮食限制感到恼火。',
      'q7_d': '我还不太了解碳水化合物计算。',
      'q8': '8. 您的身体活动水平如何？',
      'q8_a': '我定期锻炼。',
      'q8_b': '由于压力，我很难保持规律。',
      'q8_c': '我觉得很无聊，但能做就做。',
      'q8_d': '我刚刚开始。',
      'q9': '9. 您目前最大的健康挑战是什么？',
      'q9_a': '保持冷静，避免压力。',
      'q9_b': '不因正常的血糖波动感到挫败。',
      'q9_c': '不浪费时间地记住药品和库存。',
      'q9_d': '从零开始学习关于糖尿病的一切。',
      'q10': '10. 您管理糖尿病多长时间了？',
      'q10_a': '我最近才被确诊。',
      'q10_b': '已有几年，我已经很熟悉了。',
      'q10_c': '很长时间了，但仍然感到忧虑。',
      'q10_d': '很长时间了，但有时会对日常感到烦躁。',
    },
    'es': {
      'startBtn': 'INICIAR',
      'welcomeMsg': 'Cuidado inteligente para tu salud.',
      'welcome': '¡Bienvenido de nuevo!',
      'subtitle': 'Inicia sesión para acceder a tu cuenta y hablar con Diana.',
      'sponsor': 'Patrocinado por Eurofarma',
      'signin': 'Iniciar sesión',
      'signup': 'Registrarse',
      'userPlaceholder': 'Correo electrónico',
      'namePlaceholder': 'Nombre completo',
      'passPlaceholder': 'Contraseña',
      'newHere': '¿Nuevo por aquí?',
      'createAccount': 'Crear una cuenta',
      'alreadyHaveAccount': '¿Ya tienes una cuenta?',
      'dianaTitle': 'Diana',
      'dianaSub': 'Asistente Virtual de Salud Eurofarma',
      'dianaChatPlaceholder': 'Escribe tu duda sobre rutina o glucemia...',
      'medReminder': 'Mis Medicamentos',
      'addMed': 'Agregar Medicamento',
      'medName': 'Nombre del medicamento',
      'medSchedule': 'Horarios (ej.: 08:00, 20:00)',
      'medStock': 'Stock actual (unidades)',
      'medDaily': 'Consumo diario (unidades)',
      'save': 'Guardar',
      'stockSuffix': 'días restantes. ¡Hora de reponer!',
      'stockSafe': 'Stock seguro para más de',
      'days': 'días.',
      'dianaGreeting': '¡Hola! Soy **Diana**, tu asistente de salud de Eurofarma. ¿Cómo puedo ayudarte hoy con tu rutina de glucemia?',
      'errorAuth': 'Usuario o contraseña incorrectos.',
      'errorEmpty': 'Por favor, completa todos los campos.',
      'successRegister': '¡Cuenta creada con éxito! Por favor responde al cuestionario de perfil.',
      'dianaThinking': 'Diana está escribiendo...',
      'notifTitle': '¿Permitir notificaciones?',
      'notifBody': 'GlicoCare desea enviarte recordatorios de medicamentos y alertas de stock.',
      'allow': 'Permitir',
      'deny': 'Ahora no',
      'chip1': '🍎 Alimentos recomendados',
      'chip2': '💊 Consejo de medicación',
      'chip3': '📊 ¿Qué hacer en hipoglucemia?',
      'profileTitle': 'Perfil de Usuario',
      'close': 'Cerrar',
      'questionTitle': 'Cuestionario de Perfil',
      'q1': '1. Cuando tu glucemia se sale de lo esperado, ¿cuál es tu primera reacción?',
      'q1_a': 'Me preocupo mucho y la reviso todo el tiempo.',
      'q1_b': 'Me irrito y me dan ganas de ignorarlo.',
      'q1_c': 'Lo afronto de forma objetiva y sigo el plan.',
      'q1_d': 'Me siento perdido/a y sin saber qué hacer.',
      'q2': '2. ¿Cómo prefieres gestionar los momentos de estrés o desafíos?',
      'q2_a': 'Necesito contención y una conversación tranquila.',
      'q2_b': 'Busco datos y explicaciones muy directas.',
      'q2_c': 'Prefiero algo ligero para aliviar la carga.',
      'q2_d': 'Necesito orientaciones paso a paso.',
      'q3': '3. ¿Qué tono de conversación detestas más?',
      'q3_a': 'Un tono regañón o de profesor.',
      'q3_b': 'Discursos muy largos y sin objetividad.',
      'q3_c': 'Falta de empatía o frialdad.',
      'q3_d': 'Términos muy complejos o difíciles.',
      'q4': '4. ¿Cómo quieres que Diana hable contigo?',
      'q4_a': 'Acogedora y tranquila (enfocada en tranquilizar).',
      'q4_b': 'Directa y objetiva (enfocada en datos y viñetas).',
      'q4_c': 'Motivadora y ligera (enfocada en incentivos).',
      'q4_d': 'Educativa y detallada (explicando lo básico con paciencia).',
      'q5': '5. ¿Cuál es tu preferencia con respecto a los recordatorios?',
      'q5_a': 'Avisos suaves y afectuosos.',
      'q5_b': 'Recordatorios cortos y directos.',
      'q5_c': 'Avisos con un toque de incentivo.',
      'q5_d': 'Recordatorios explicativos sobre el motivo de la dosis.',
      'q6': '6. ¿Cómo es el ritmo de tu rutina diaria?',
      'q6_a': 'Muy ajetreado, me genera ansiedad.',
      'q6_b': 'Estructurado y bien planificado.',
      'q6_c': 'Un poco impredecible y agitado.',
      'q6_d': 'Todavía estoy intentando organizar mi rutina.',
      'q7': '7. ¿Cómo sueles alimentarte?',
      'q7_a': 'Sigo mi plan con disciplina.',
      'q7_b': 'Tengo ansiedad y termino desquitándome con la comida.',
      'q7_c': 'A veces me molesta tener limitaciones en la dieta.',
      'q7_d': 'Aún no entiendo bien el conteo de carbohidratos.',
      'q8': '8. ¿Cuál es tu nivel de actividad física?',
      'q8_a': 'Hago ejercicio con regularidad.',
      'q8_b': 'Me cuesta mantener la constancia por el estrés.',
      'q8_c': 'Me parece aburrido pero lo hago cuando puedo.',
      'q8_d': 'Estoy empezando ahora.',
      'q9': '9. ¿Cuál es tu mayor desafío actual con tu salud?',
      'q9_a': 'Mantener la calma y no estresarme.',
      'q9_b': 'No frustrarme con las oscilaciones normales.',
      'q9_c': 'Recordar medicamentos y stock sin perder tiempo.',
      'q9_d': 'Aprender todo sobre la diabetes desde cero.',
      'q10': '10. ¿Cuánto tiempo llevas gestionando la diabetes?',
      'q10_a': 'Me la diagnosticaron hace poco.',
      'q10_b': 'Hace unos años y ya la conozco bien.',
      'q10_c': 'Hace mucho tiempo, pero aún me siento aprensivo/a.',
      'q10_d': 'Hace tiempo, pero tengo días de enfado con la rutina.',
    },
    'it': {
      'startBtn': 'INIZIA',
      'welcomeMsg': 'Cura intelligente per la tua salute.',
      'welcome': 'Bentornato!',
      'subtitle': 'Accedi per accedere al tuo account e parlare con Diana.',
      'sponsor': 'Sponsorizzato da Eurofarma',
      'signin': 'Accedi',
      'signup': 'Registrati',
      'userPlaceholder': 'E-mail',
      'namePlaceholder': 'Nome Completo',
      'passPlaceholder': 'Password',
      'newHere': 'Nuovo qui?',
      'createAccount': 'Crea un account',
      'alreadyHaveAccount': 'Hai già un account?',
      'dianaTitle': 'Diana',
      'dianaSub': 'Assistente Virtuale per la Salute Eurofarma',
      'dianaChatPlaceholder': 'Scrivi la tua domanda sulla routine o sulla glicemia...',
      'medReminder': 'I Miei Farmaci',
      'addMed': 'Aggiungi Farmaco',
      'medName': 'Nome del farmaco',
      'medSchedule': 'Orari (es.: 08:00, 20:00)',
      'medStock': 'Scorta attuale (unità)',
      'medDaily': 'Consumo giornaliero (unità)',
      'save': 'Salva',
      'stockSuffix': 'giorni rimasti. È ora di rifornire!',
      'stockSafe': 'Scorta sicura per più di',
      'days': 'giorni.',
      'dianaGreeting': 'Ciao! Sono **Diana**, la tua assistente sanitaria Eurofarma. Come posso aiutarti oggi a gestire la tua routine di glicemia?',
      'errorAuth': 'E-mail o password errate.',
      'errorEmpty': 'Si prega di compilare tutti i campi.',
      'successRegister': 'Account creato con successo! Rispondi al questionario sul profilo.',
      'dianaThinking': 'Diana sta scrivendo...',
      'notifTitle': 'Consentire le notifiche?',
      'notifBody': 'GlicoCare desidera inviarti promemoria sui farmaci e avvisi sulle scorte.',
      'allow': 'Consenti',
      'deny': 'Non ora',
      'chip1': '🍎 Cibi consigliati',
      'chip2': '💊 Consiglio sul farmaco',
      'chip3': '📊 Cosa fare in caso di ipoglicemia?',
      'profileTitle': 'Profilo Utente',
      'close': 'Chiudi',
      'questionTitle': 'Questionario sul Profilo',
      'q1': '1. Quando la tua glicemia va fuori bersaglio, qual è la tua prima reazione?',
      'q1_a': 'Mi preoccupo molto e la controllo di continuo.',
      'q1_b': 'Mi innervosisco e vorrei lasciar perdere.',
      'q1_c': 'La affronto in modo obiettivo e seguo il piano.',
      'q1_d': 'Mi sento smarrito/a e non so cosa fare.',
      'q2': '2. Come preferisci gestire momenti di stress o sfide?',
      'q2_a': 'Ho bisogno di accoglienza e di una conversazione calma.',
      'q2_b': 'Certo dati e spiegazioni dirette.',
      'q2_c': 'Preferisco leggerezza per alleviare il peso.',
      'q2_d': 'Ho bisogno di indicazioni passo dopo passo.',
      'q3': '3. Quale tono di conversazione detesti di più?',
      'q3_a': 'Un tono severo o cattedratico.',
      'q3_b': 'Discorsi troppo lunghi e privi di oggettività.',
      'q3_c': 'Mancanza di empatia o freddezza.',
      'q3_d': 'Termini troppo complessi o difficili.',
      'q4': '4. Come vorresti che Diana ti parlasse?',
      'q4_a': 'Accogliente e calma (focalizzata nel rassicurare).',
      'q4_b': 'Diretta e obiettiva (focalizzata su dati e punti chiave).',
      'q4_c': 'Incoraggiante e leggera (focalizzata sulle motivazioni).',
      'q4_d': 'Educativa e dettagliata (spiegando le basi con pazienza).',
      'q5': '5. Qual è la tua preferenza per i promemoria?',
      'q5_a': 'Avvisi leggeri e cordiali.',
      'q5_b': 'Promemoria brevi e diretti.',
      'q5_c': 'Avvisi con un tocco di incoraggiamento.',
      'q5_d': 'Promemoria esplicativi sui motivi della dose.',
      'q6': '6. Com\'è il ritmo della tua routine quotidiana?',
      'q6_a': 'Molto frenetico, mi provoca ansia.',
      'q6_b': 'Strutturato e ben pianificato.',
      'q6_c': 'Un po\' imprevedibile e agitato.',
      'q6_d': 'Sto ancora cercando di organizzare la mia routine.',
      'q7': '7. Come gestisci di solito l\'alimentazione?',
      'q7_a': 'Seguo il mio piano con disciplina.',
      'q7_b': 'Ho ansia e finisco per sfogarmi sul cibo.',
      'q7_c': 'A volte mi innervosce avere limitazioni nella dieta.',
      'q7_d': 'Non capisco ancora bene il conteggio dei carboidrati.',
      'q8': '8. Qual è il tuo livello di attività fisica?',
      'q8_a': 'Faccio esercizio regolarmente.',
      'q8_b': 'Faccio fatica a mantenere la costanza per lo stress.',
      'q8_c': 'Lo trovo noioso ma lo faccio quando posso.',
      'q8_d': 'Sto iniziando adesso.',
      'q9': '9. Qual è la tua sfida principale con la salute in questo momento?',
      'q9_a': 'Mantenere la calma ed evitare lo stress.',
      'q9_b': 'Non frustrarmi per le normali oscillazioni.',
      'q9_c': 'Ricordare farmaci e scorte senza perdere tempo.',
      'q9_d': 'Imparare tutto sul diabete da zero.',
      'q10': '10. Da quanto tempo gestisci il diabete?',
      'q10_a': 'Mi è stato diagnosticato da poco.',
      'q10_b': 'Da qualche anno e lo conosco bene.',
      'q10_c': 'Da molto tempo, ma sono ancora apprensivo/a.',
      'q10_d': 'Da molto tempo, ma ho giorni di rabbia verso la routine.',
    },
    'fr': {
      'startBtn': 'COMMENCER',
      'welcomeMsg': 'Des soins intelligents pour votre santé.',
      'welcome': 'Bon retour !',
      'subtitle': 'Connectez-vous pour accéder à votre compte et parler à Diana.',
      'sponsor': 'Sponsorisé par Eurofarma',
      'signin': 'Se connecter',
      'signup': 'S\'inscrire',
      'userPlaceholder': 'E-mail',
      'namePlaceholder': 'Nom Complet',
      'passPlaceholder': 'Mot de passe',
      'newHere': 'Nouveau ici ?',
      'createAccount': 'Créer un compte',
      'alreadyHaveAccount': 'Vous avez déjà un compte ?',
      'dianaTitle': 'Diana',
      'dianaSub': 'Assistant Virtuel de Santé Eurofarma',
      'dianaChatPlaceholder': 'Saisissez votre question sur votre routine ou glycémie...',
      'medReminder': 'Mes Médicaments',
      'addMed': 'Ajouter un Médicament',
      'medName': 'Nom du médicament',
      'medSchedule': 'Horaires (ex. : 08:00, 20:00)',
      'medStock': 'Stock actuel (unités)',
      'medDaily': 'Consommation quotidienne (unités)',
      'save': 'Enregistrer',
      'stockSuffix': 'jours restants. Temps de réapprovisionner !',
      'stockSafe': 'Stock sécurisé pour plus de',
      'days': 'jours.',
      'dianaGreeting': 'Bonjour ! Je suis **Diana**, votre assistante santé Eurofarma. Comment puis-je vous aider aujourd\'hui ?',
      'errorAuth': 'E-mail ou mot de passe incorrect.',
      'errorEmpty': 'Veuillez remplir tous les champs.',
      'successRegister': 'Compte créé avec succès ! Veuillez répondre au questionnaire de profil.',
      'dianaThinking': 'Diana écrit...',
      'notifTitle': 'Autoriser les notifications ?',
      'notifBody': 'GlicoCare souhaite vous envoyer des rappels de médicaments et des alertes de stock.',
      'allow': 'Autoriser',
      'deny': 'Pas maintenant',
      'chip1': '🍎 Aliments recommandés',
      'chip2': '💊 Conseil médicament',
      'chip3': '📊 Que faire en cas d\'hypoglycémie ?',
      'profileTitle': 'Profil Utilisateur',
      'close': 'Fermer',
      'questionTitle': 'Questionnaire de Profil',
      'q1': '1. Lorsque votre glycémie s\'écarte de l\'objectif, quelle est votre première réaction ?',
      'q1_a': 'Je m\'inquiète beaucoup et je la vérifie constamment.',
      'q1_b': 'Je m\'énerve et j\'ai envie de laisser tomber.',
      'q1_c': 'Je gère cela objectivement et je me conforme au plan.',
      'q1_d': 'Je me sens perdu(e) et ne sais pas quoi faire.',
      'q2': '2. Comment préférez-vous gérer les moments de stress ou les défis ?',
      'q2_a': 'J\'ai besoin de réconfort et d\'une conversation calme.',
      'q2_b': 'Je cherche des données et des explications directes.',
      'q2_c': 'Je préfère la légèreté pour soulager le poids.',
      'q2_d': 'J\'ai besoin d\'instructions pas à pas.',
      'q3': '3. Quel ton de conversation détestez-vous le plus ?',
      'q3_a': 'Un ton moralisateur ou professoral.',
      'q3_b': 'Les longs discours manquant d\'objectivité.',
      'q3_c': 'Le manque d\'empathie ou la froideur.',
      'q3_d': 'Des termes trop complexes ou difficiles.',
      'q4': '4. Comment souhaitez-vous que Diana vous parle ?',
      'q4_a': 'Accueillante et calme (centrée sur le réconfort).',
      'q4_b': 'Directe et objective (centrée sur les données et les points clés).',
      'q4_c': 'Encourageante et légère (centrée sur la motivation).',
      'q4_d': 'Éducative et détaillée (expliquant les bases avec patience).',
      'q5': '5. Quelle est votre préférence concernant les rappels ?',
      'q5_a': 'Des notifications douces et bienveillantes.',
      'q5_b': 'Des rappels brefs et directs.',
      'q5_c': 'Des avis avec une touche d\'encouragement.',
      'q5_d': 'Des rappels explicatifs indiquant la raison de la dose.',
      'q6': '6. Quel est le rythme de votre routine quotidienne ?',
      'q6_a': 'Très intense, cela me génère de l\'anxiété.',
      'q6_b': 'Structuré et bien planifié.',
      'q6_c': 'Un peu imprévisible et agité.',
      'q6_d': 'J\'essaie encore d\'organiser ma routine.',
      'q7': '7. Comment gérez-vous habituellement votre alimentation ?',
      'q7_a': 'Je suis mon programme avec discipline.',
      'q7_b': 'Ressentant de l\'anxiété, je me venge sur la nourriture.',
      'q7_c': 'Parfois, les restrictions me pèsent.',
      'q7_d': 'Je ne maîtrise pas encore bien le calcul des glucides.',
      'q8': '8. Quel est votre niveau d\'activité physique ?',
      'q8_a': 'Je fais de l\'exercice régulièrement.',
      'q8_b': 'J\'ai du mal à être régulier en raison du stress.',
      'q8_c': 'Je trouve cela ennuyeux mais je le fais quand c\'est possible.',
      'q8_d': 'Je débute à peine.',
      'q9': '9. Quel est votre plus grand défi de santé actuel ?',
      'q9_a': 'Garder mon calme et éviter le stress.',
      'q9_b': 'Ne pas me frustrer face aux variations normales.',
      'q9_c': 'Penser aux médicaments et au stock sans perdre de temps.',
      'q9_d': 'Tout apprendre sur le diabète en partant de zéro.',
      'q10': '10. Depuis combien de temps gérez-vous votre diabète ?',
      'q10_a': 'Le diagnostic est récent.',
      'q10_b': 'Depuis quelques années, je connais bien le sujet.',
      'q10_c': 'Depuis longtemps, mais je ressens toujours de l\'appréhension.',
      'q10_d': 'Depuis longtemps, mais j\'ai des jours de colère contre la routine.',
    },
    'de': {
      'startBtn': 'STARTEN',
      'welcomeMsg': 'Intelligente Pflege für Ihre Gesundheit.',
      'welcome': 'Willkommen zurück!',
      'subtitle': 'Melden Sie sich an, um auf Ihr Konto zuzugreifen und mit Diana zu sprechen.',
      'sponsor': 'Gesponsert von Eurofarma',
      'signin': 'Anmelden',
      'signup': 'Registrieren',
      'userPlaceholder': 'E-Mail',
      'namePlaceholder': 'Vollständiger Name',
      'passPlaceholder': 'Passwort',
      'newHere': 'Neu hier?',
      'createAccount': 'Konto erstellen',
      'alreadyHaveAccount': 'Bereits ein Konto?',
      'dianaTitle': 'Diana',
      'dianaSub': 'Eurofarma Virtueller Gesundheitsassistent',
      'dianaChatPlaceholder': 'Geben Sie Ihre Frage zu Routine oder Blutzucker ein...',
      'medReminder': 'Meine Medikamente',
      'addMed': 'Medikament hinzufügen',
      'medName': 'Medikamentenname',
      'medSchedule': 'Zeiten (z. B. 08:00, 20:00)',
      'medStock': 'Aktueller Vorrat (Einheiten)',
      'medDaily': 'Täglicher Verbrauch (Einheiten)',
      'save': 'Speichern',
      'stockSuffix': 'Tage verbleibend. Zeit nachzufüllen!',
      'stockSafe': 'Sicherer Vorrat für mehr als',
      'days': 'Tage.',
      'dianaGreeting': 'Hallo! Ich bin **Diana**, Ihre Eurofarma-Gesundheitsassistentin. Wie kann ich Ihnen heute helfen?',
      'errorAuth': 'E-Mail oder Passwort falsch.',
      'errorEmpty': 'Bitte füllen Sie alle Felder aus.',
      'successRegister': 'Konto erfolgreich erstellt! Bitte beantworten Sie den Profilfragebogen.',
      'dianaThinking': 'Diana schreibt...',
      'notifTitle': 'Benachrichtigungen zulassen?',
      'notifBody': 'GlicoCare möchte Ihnen Medikamentenerinnerungen und Vorratswarnungen senden.',
      'allow': 'Zulassen',
      'deny': 'Nicht jetzt',
      'chip1': '🍎 Empfohlene Lebensmittel',
      'chip2': '💊 Medikamenten-Tipp',
      'chip3': '📊 Was tun bei Unterzuckerung?',
      'profileTitle': 'Benutzerprofil',
      'close': 'Schließen',
      'questionTitle': 'Profil-Fragebogen',
      'q1': '1. Wenn Ihr Blutzucker abweicht, was ist Ihre erste Reaktion?',
      'q1_a': 'Ich mache mir große Sorgen und überprüfe ihn ständig.',
      'q1_b': 'Ich bin verärgert und möchte es ignorieren.',
      'q1_c': 'Ich gehe objektiv damit um und folge dem Plan.',
      'q1_d': 'Ich fühle mich hilflos und weiß nicht, was ich tun soll.',
      'q2': '2. Wie bewältigen Sie Stress oder Herausforderungen am liebsten?',
      'q2_a': 'Ich brauche Mitgefühl und ein ruhiges Gespräch.',
      'q2_b': 'Ich suche nach Daten und direkten Erklärungen.',
      'q2_c': 'Ich bevorzuge Leichtigkeit, um den Druck zu mindern.',
      'q2_d': 'Ich brauche eine Schritt-für-Schritt-Anleitung.',
      'q3': '3. Welchen Gesprächston mögen Sie am wenigsten?',
      'q3_a': 'Einen belehrenden oder strengen Ton.',
      'q3_b': 'Lange Reden ohne Auf den Punkt zu kommen.',
      'q3_c': 'Mangelnde Empathie oder Kälte.',
      'q3_d': 'Zu komplexe oder schwierige Begriffe.',
      'q4': '4. Wie soll Diana mit Ihnen sprechen?',
      'q4_a': 'Einfühlsam und ruhig (Fokus auf Beruhigung).',
      'q4_b': 'Direkt und objektiv (Fokus auf Daten und Stichpunkte).',
      'q4_c': 'Ermutigend und leicht (Fokus auf Motivation).',
      'q4_d': 'Lehrreich und detailliert (Grundlagen geduldig erklären).',
      'q5': '5. Was bevorzugen Sie bei Erinnerungen?',
      'q5_a': 'Sanfte und freundliche Hinweise.',
      'q5_b': 'Kurze und direkte Erinnerungen.',
      'q5_c': 'Erinnerungen mit einem ermutigenden Ton.',
      'q5_d': 'Erklärende Hinweise zum Grund der Dosis.',
      'q6': '6. Wie ist das Tempo Ihrer täglichen Routine?',
      'q6_a': 'Sehr hektisch, es verursacht mir Angstzustände.',
      'q6_b': 'Strukturiert und gut geplant.',
      'q6_c': 'Etwas unvorhersehbar und geschäftig.',
      'q6_d': 'Ich versuche noch, meine Routine zu organisieren.',
      'q7': '7. Wie gestalten Sie meist Ihre Ernährung?',
      'q7_a': 'Ich folge meinem Plan diszipliniert.',
      'q7_b': 'Ich habe Angst und esse dann Frust.',
      'q7_c': 'Manchmal ärgern mich die Einschränkungen.',
      'q7_d': 'Ich verstehe das Kohlenhydratzählen noch nicht gut.',
      'q8': '8. Wie hoch ist Ihr körperliches Aktivitätsniveau?',
      'q8_a': 'Ich treibe regelmäßig Sport.',
      'q8_b': 'Es fällt mir schwer, wegen Stress konstant zu bleiben.',
      'q8_c': 'Ich finde es langweilig, mache es aber wenn möglich.',
      'q8_d': 'Ich fange gerade erst an.',
      'q9': '9. Was ist derzeit Ihre größte gesundheitliche Herausforderung?',
      'q9_a': 'Ruhig zu bleiben und Stress zu vermeiden.',
      'q9_b': 'Mich nicht über normale Schwankungen zu ärgern.',
      'q9_c': 'An Medikamente und Vorrat zu denken, ohne Zeit zu verlieren.',
      'q9_d': 'Alles über Diabetes von Grund auf zu lernen.',
      'q10': '10. Wie lange verwalten Sie Diabetes schon?',
      'q10_a': 'Die Diagnose ist noch recht neu.',
      'q10_b': 'Seit einigen Jahren und ich kenne mich gut aus.',
      'q10_c': 'Schon lange, aber ich bin immer noch besorgt.',
      'q10_d': 'Schon lange, aber ich habe Tage voller Wut auf die Routine.',
    },
    'ko': {
      'startBtn': '지금 시작하기',
      'welcomeMsg': '건강 관리를 위한 스마트 어시스턴트',
      'welcome': '다시 오신 것을 환영합니다!',
      'subtitle': '계정에 접속하고 Diana와 대화하려면 로그인하세요.',
      'sponsor': 'Eurofarma 후원',
      'signin': '로그인',
      'signup': '회원가입',
      'userPlaceholder': '이메일',
      'namePlaceholder': '이름',
      'passPlaceholder': '비밀번호',
      'newHere': '처음 방문하셨나요?',
      'createAccount': '계정 만들기',
      'alreadyHaveAccount': '이미 계정이 있으신가요?',
      'dianaTitle': 'Diana',
      'dianaSub': 'Eurofarma 가상 의료 어시스턴트',
      'dianaChatPlaceholder': '약이나 혈당 수치에 대해 질문을 입력하세요...',
      'medReminder': '내 약',
      'addMed': '약 추가',
      'medName': '약 이름',
      'medSchedule': '복용 시간 (예: 08:00, 20:00)',
      'medStock': '남은 수량',
      'medDaily': '일일 복용량',
      'save': '저장',
      'stockSuffix': '일 남음 (재고 부족)',
      'stockSafe': '안전 재고 보유 (이상)',
      'days': '일.',
      'dianaGreeting': '안녕하세요! 저는 Eurofarma의 가상 어시스턴트 Diana입니다. 오늘 혈당 관리를 어떻게 도와드릴까요?',
      'errorAuth': '이메일 또는 비밀번호가 올바르지 않습니다.',
      'errorEmpty': '모든 항목을 입력해 주세요.',
      'successRegister': '계정이 성공적으로 생성되었습니다!',
      'dianaThinking': 'Diana가 입력하고 있습니다...',
      'notifTitle': '알림을 활성화하시겠습니까?',
      'notifBody': '약 복용 시간과 혈당 측정 시간을 알려주는 알림을 받으세요.',
      'allow': '허용',
      'deny': '나중에',
      'chip1': '🍎 추천 음식',
      'chip2': '💊 약 복용 팁',
      'chip3': '📊 혈당이 낮아졌을 때 어떻게 해야 하나요?',
      'profileTitle': '사용자 프로필',
      'close': '닫기',
      'questionTitle': '질문',
      'q1': '1. 혈당이 목표 범위를 벗어났을 때, 가장 먼저 어떤 반응을 보이나요?',
      'q1_a': '매우 걱정되어 계속 확인합니다.',
      'q1_b': '짜증이 나고 그냥 무시하고 싶어집니다.',
      'q1_c': '객관적으로 받아들이고 계획을 따릅니다.',
      'q1_d': '막막하고 무엇을 해야 할지 모르겠습니다.',
      'q2': '2. 스트레스나 어려운 상황을 어떻게 대처하는 것을 선호하나요?',
      'q2_a': '위로와 차분한 대화가 필요합니다.',
      'q2_b': '데이터와 직접적인 설명을 찾습니다.',
      'q2_c': '부담을 덜기 위해 편안하고 가벼운 분위기를 선호합니다.',
      'q2_d': '단계별 안내가 필요합니다.',
      'q3': '3. 어떤 대화 방식이 가장 싫나요?',
      'q3_a': '혼내거나 가르치려 드는 말투.',
      'q3_b': '핵심 없이 너무 긴 설명.',
      'q3_c': '공감이 없거나 차가운 태도.',
      'q3_d': '너무 복잡하거나 어려운 용어.',
      'q4': '4. Diana가 어떤 방식으로 이야기해 주기를 원하나요?',
      'q4_a': '따뜻하고 차분하게 (안심시키는 데 중점).',
      'q4_b': '직접적이고 객관적으로 (데이터와 핵심 내용에 중점).',
      'q4_c': '격려하고 편안하게 (동기 부여에 중점).',
      'q4_d': '교육적이고 자세하게 (기본 내용을 인내심 있게 설명).',
      'q5': '5. 알림에 대해 어떤 방식을 선호하나요?',
      'q5_a': '부드럽고 친절한 알림.',
      'q5_b': '짧고 직접적인 알림.',
      'q5_c': '격려하는 느낌이 담긴 알림.',
      'q5_d': '복용 이유를 설명해 주는 알림.',
      'q6': '6. 평소 일상생활의 속도는 어떤가요?',
      'q6_a': '매우 바빠서 불안해집니다.',
      'q6_b': '체계적이고 잘 계획되어 있습니다.',
      'q6_c': '조금 예측하기 어렵고 바쁩니다.',
      'q6_d': '아직 일상을 정리하려고 노력하는 중입니다.',
      'q7': '7. 평소 식사는 어떻게 관리하나요?',
      'q7_a': '계획을 규칙적으로 따릅니다.',
      'q7_b': '불안해서 결국 음식으로 스트레스를 풉니다.',
      'q7_c': '가끔 식단 제한 때문에 속상합니다.',
      'q7_d': '아직 탄수화물 계산을 잘 이해하지 못합니다.',
      'q8': '8. 신체 활동 수준은 어떤가요?',
      'q8_a': '규칙적으로 운동합니다.',
      'q8_b': '스트레스 때문에 꾸준히 하기 어렵습니다.',
      'q8_c': '재미없다고 느끼지만 가능할 때 합니다.',
      'q8_d': '지금 막 시작하고 있습니다.',
      'q9': '9. 현재 건강 관리에서 가장 큰 어려움은 무엇인가요?',
      'q9_a': '침착함을 유지하고 스트레스를 피하는 것.',
      'q9_b': '정상적인 변동 때문에 좌절하지 않는 것.',
      'q9_c': '시간을 낭비하지 않고 약과 재고를 기억하는 것.',
      'q9_d': '당뇨병에 대해 처음부터 모든 것을 배우는 것.',
      'q10': '10. 당뇨병을 관리한 지 얼마나 되었나요?',
      'q10_a': '최근에 진단받았습니다.',
      'q10_b': '몇 년 되었고 잘 알고 있습니다.',
      'q10_c': '오래되었지만 아직도 걱정될 때가 있습니다.',
      'q10_d': '오래되었지만 일상적인 관리에 화가 나는 날도 있습니다.',
    },
    'ja': {
      'startBtn': '開始',
      'welcomeMsg': 'あなたの健康のためのスマートケア。',
      'welcome': 'おかえりなさい！',
      'subtitle': 'ログインしてアカウントにアクセスし、Dianaと話しましょう。',
      'sponsor': 'Eurofarma提供',
      'signin': 'ログイン',
      'signup': '新規登録',
      'userPlaceholder': 'メールアドレス',
      'namePlaceholder': 'フルネーム',
      'passPlaceholder': 'パスワード',
      'newHere': '初めての方はこちら',
      'createAccount': 'アカウントを作成',
      'alreadyHaveAccount': 'すでにアカウントをお持ちですか？',
      'dianaTitle': 'Diana',
      'dianaSub': 'Eurofarmaバーチャルヘルスアシスタント',
      'dianaChatPlaceholder': '日常生活や血糖値についての質問を入力してください...',
      'medReminder': '私の服薬情報',
      'addMed': '薬を追加',
      'medName': '薬の名前',
      'medSchedule': '服用時間（例：08:00、20:00）',
      'medStock': '現在の在庫（単位）',
      'medDaily': '1日の使用量（単位）',
      'save': '保存',
      'stockSuffix': '日分残っています。補充の時期です！',
      'stockSafe': '十分な在庫があります（残り）：',
      'days': '日分。',
      'dianaGreeting': 'こんにちは！私は**Diana**です。Eurofarmaのヘルスアシスタントです。本日は血糖値の管理についてどのようなサポートをいたしましょうか？',
      'errorAuth': 'メールアドレスまたはパスワードが正しくありません。',
      'errorEmpty': 'すべての項目を入力してください。',
      'successRegister': 'アカウントの作成が完了しました！プロフィールアンケートにご回答ください。',
      'dianaThinking': 'Diana capitalization入力中...',
      'notifTitle': '通知を許可しますか？',
      'notifBody': 'GlicoCareは服薬のリマインダーや在庫のアラートを送信します。',
      'allow': '許可する',
      'deny': '後で',
      'chip1': '🍎 おすすめの食品',
      'chip2': '💊 服薬のアドバイス',
      'chip3': '📊 低血糖の時の対処法',
      'profileTitle': 'ユーザープロフィール',
      'close': '閉じる',
      'questionTitle': 'プロフィールアンケート',
      'q1': '1. 血糖値が目標から外れた時、最初の反応は？',
      'q1_a': 'とても心配になり、何度も確認してしまう。',
      'q1_b': 'イライラして放っておきたくなる。',
      'q1_c': '客観的に受け止め、計画に従う。',
      'q1_d': 'どうしていいかわからず途方に暮れる。',
      'q2': '2. ストレスや困難にはどのように対処したいですか？',
      'q2_a': '優しさと穏やかな会話が必要。',
      'q2_b': '直接的なデータや説明を求める。',
      'q2_c': '負担を減らすために気楽な対応が良い。',
      'q2_d': 'ステップ・バイ・ステップの指示が必要。',
      'q3': '3. 一番苦手な会話のトーンは？',
      'q3_a': '説教くさい・説教的なトーン。',
      'q3_b': '要点のない長話。',
      'q3_c': '共感のない冷たい対応。',
      'q3_d': '複雑すぎる用語や難しい表現。',
      'q4': '4. Dianaにはに話しかけてほしいですか？',
      'q4_a': '温かく穏やか（安心感重視）。',
      'q4_b': '的確で客観的（データや要点重視）。',
      'q4_c': '前向きで気楽（無理のない応援重視）。',
      'q4_d': '丁寧で細やか（基本を根気強く説明）。',
      'q5': '5. リマインダーの好みは？',
      'q5_a': '優しく丁寧な通知。',
      'q5_b': '簡潔で直接的なリマインダー。',
      'q5_c': '励ましの言葉が入った通知。',
      'q5_d': '服薬理由が書かれた説明的なリマインダー。',
      'q6': '6. 普段の生活リズムは？',
      'q6_a': 'とても多忙で不安を感じやすい。',
      'q6_b': '規則正しく計画的。',
      'q6_c': '少し不規則で忙しい。',
      'q6_d': 'まだリズムを整えようとしている段階。',
      'q7': '7. 普段の食生活はどうですか？',
      'q7_a': '自律して計画通りに行っている。',
      'q7_b': 'ストレスでドカ食いしてしまうことがある。',
      'q7_c': '食事制限に嫌気がさすことがある。',
      'q7_d': 'カーボカウントがまだよくわからない。',
      'q8': '8. 運動の頻度はどのくらいですか？',
      'q8_a': '定期的に運動している。',
      'q8_b': 'ストレスで継続するのが難しい。',
      'q8_c': '退屈だけどできる時にやっている。',
      'q8_d': 'ちょうど始めたばかり。',
      'q9': '9. 現在の健康管理で一番の課題は？',
      'q9_a': '気持ちを落ち着かせストレスを避けること。',
      'q9_b': '通常の変動に落ち込まないこと。',
      'q9_c': '時間をかけずに薬と在庫を管理すること。',
      'q9_d': '糖尿病について一から学ぶこと。',
      'q10': '10. 糖尿病と付き合ってどのくらいですか？',
      'q10_a': '最近診断されたばかり。',
      'q10_b': '数年経っており、よく理解している。',
      'q10_c': '長いが、今でも不安に思うことがある。',
      'q10_d': '長いが、毎日の習慣に嫌気がさす日がある。',
    },
    'hi': {
      'startBtn': 'शुरू करें',
      'welcomeMsg': 'आपकी सेहत की स्मार्ट देखभाल।',
      'welcome': 'वापसी पर स्वागत है!',
      'subtitle': 'अपने खाते तक पहुँचने और डायना से बात करने के लिए लॉग इन करें।',
      'sponsor': 'Eurofarma द्वारा प्रायोजित',
      'signin': 'लॉग इन करें',
      'signup': 'साइन अप करें',
      'userPlaceholder': 'ईमेल',
      'namePlaceholder': 'पूरा नाम',
      'passPlaceholder': 'पासवर्ड',
      'newHere': 'यहाँ नए हैं?',
      'createAccount': 'खाता बनाएं',
      'alreadyHaveAccount': 'पहले से खाता है?',
      'dianaTitle': 'डायना',
      'dianaSub': 'Eurofarma वर्चुअल हेल्थ असिस्टेंट',
      'dianaChatPlaceholder': 'अपनी दिनचर्या या ब्लड शुगर के बारे में प्रश्न टाइप करें...',
      'medReminder': 'मेरी दवाएं',
      'addMed': 'दवा जोड़ें',
      'medName': 'दवा का नाम',
      'medSchedule': 'समय (उदा: 08:00, 20:00)',
      'medStock': 'वर्तमान स्टॉक (इकाइयां)',
      'medDaily': 'दैनिक खपत (इकाइयां)',
      'save': 'सहेजें',
      'stockSuffix': 'दिन शेष। स्टॉक पूरा करने का समय!',
      'stockSafe': 'सुरक्षित स्टॉक से अधिक के लिए',
      'days': 'दिन।',
      'dianaGreeting': 'नमस्ते! मैं **डायना** हूँ, आपकी Eurofarma स्वास्थ्य सहायक। आज आपकी दिनचर्या में सहायता कैसे कर सकती हूँ?',
      'errorAuth': 'गलत ईमेल या पासवर्ड।',
      'errorEmpty': 'कृपया सभी फ़ील्ड भरें।',
      'successRegister': 'खाता सफलतापूर्वक बनाया गया! कृपया प्रोफ़ाइल प्रश्नावली पूरी करें।',
      'dianaThinking': 'डायना टाइप कर रही है...',
      'notifTitle': 'सूचनाओं की अनुमति दें?',
      'notifBody': 'GlicoCare दवा के रिमाइंडर और स्टॉक अलर्ट भेजना चाहता है।',
      'allow': 'अनुमति दें',
      'deny': 'अभी नहीं',
      'chip1': '🍎 अनुशंसित भोजन',
      'chip2': '💊 दवा का सुझाव',
      'chip3': '📊 लो ब्लड शुगर में क्या करें?',
      'profileTitle': 'उपयोगकर्ता प्रोफ़ाइल',
      'close': 'बंद करें',
      'questionTitle': 'प्रोफ़ाइल प्रश्नावली',
      'q1': '1. जब आपका ब्लड शुगर लक्ष्य से बाहर हो जाता है, तो आपकी पहली प्रतिक्रिया क्या होती है?',
      'q1_a': 'मैं बहुत चिंतित हो जाता/जाती हूँ और बार-बार जाँच करता/करती हूँ।',
      'q1_b': 'मैं चिढ़ जाता/जाती हूँ और इसे अनदेखा करने का मन करता है।',
      'q1_c': 'मैं इसे वस्तुनिष्ठ रूप से संभालता/संभालती हूँ और योजना का पालन करता/करती हूँ।',
      'q1_d': 'मैं खुद को असहाय महसूस करता/करती हूँ और समझ नहीं आता क्या करूँ।',
      'q2': '2. आप तनावपूर्ण क्षणों या चुनौतियों से निपटना कैसे पसंद करते हैं?',
      'q2_a': 'मुझे सहानुभूति और शांत बातचीत की आवश्यकता है।',
      'q2_b': 'मैं सीधे डेटा और स्पष्टीकरण की तलाश करता/करती हूँ।',
      'q2_c': 'मैं बोझ को कम करने के लिए हल्कापन पसंद करता/करती हूँ।',
      'q2_d': 'मुझे चरण-दर-चरण मार्गदर्शन की आवश्यकता है।',
      'q3': '3. आप किस प्रकार के लहजे को सबसे अधिक नापसंद करते हैं?',
      'q3_a': 'डांटने या उपदेश देने वाला लहजा।',
      'q3_b': 'बिना किसी स्पष्टता के लंबे भाषण।',
      'q3_c': 'सहानुभूति की कमी या ठंडापन।',
      'q3_d': 'अत्यधिक जटिल या कठिन शब्द।',
      'q4': '4. आप क्या चाहते हैं कि डायना आपसे कैसे बात करे?',
      'q4_a': 'आत्मीय और शांत (आश्वस्त करने पर ध्यान केंद्रित)।',
      'q4_b': 'सीधी और वस्तुनिष्ठ (डेटा और बिंदुओं पर ध्यान केंद्रित)।',
      'q4_c': 'प्रोत्साहक और हल्की (बिना दबाव के प्रेरणा पर ध्यान)।',
      'q4_d': 'शैक्षिक और विस्तृत (धैर्य के साथ बुनियादी बातें समझाना)।',
      'q5': '5. रिमाइंडर के बारे में आपकी क्या प्राथमिकता है?',
      'q5_a': 'हल्की और स्नेही सूचनाएं।',
      'q5_b': 'संक्षिप्त और सीधे रिमाइंडर।',
      'q5_c': 'प्रोत्साहन के स्पर्श के साथ नोटिस।',
      'q5_d': 'खुराक का कारण बताने वाले व्याख्यात्मक रिमाइंडर।',
      'q6': '6. आपकी दैनिक दिनचर्या की गति कैसी है?',
      'q6_a': 'बहुत व्यस्त, इससे मुझे चिंता होती है।',
      'q6_b': 'संरचित और अच्छी तरह से नियोजित।',
      'q6_c': 'थोड़ी अप्रत्याशित और व्यस्त।',
      'q6_d': 'मैं अभी भी अपनी दिनचर्या को व्यवस्थित करने का प्रयास कर रहा/रही हूँ।',
      'q7': '7. आप आमतौर पर अपने आहार का प्रबंधन कैसे करते हैं?',
      'q7_a': 'मैं अनुशासन के साथ अपनी योजना का पालन करता/करती हूँ।',
      'q7_b': 'मुझे चिंता होती है और अंत में भोजन पर गुस्सा निकालता/निकालती हूँ।',
      'q7_c': 'कभी-कभी आहार प्रतिबंधों से परेशान हो जाता/जाती हूँ।',
      'q7_d': 'मुझे अभी भी कार्बोहाइड्रेट की गिनती अच्छी तरह समझ नहीं आती।',
      'q8': '8. आपका शारीरिक गतिविधि स्तर क्या है?',
      'q8_a': 'मैं नियमित रूप से व्यायाम करता/करती हूँ।',
      'q8_b': 'तनाव के कारण निरंतरता बनाए रखना कठिन होता है।',
      'q8_c': 'मुझे यह उबाऊ लगता है लेकिन जब संभव हो करता/करती हूँ।',
      'q8_d': 'मैं अभी शुरुआत कर रहा/रही हूँ।',
      'q9': '9. इस समय आपकी स्वास्थ्य संबंधी सबसे बड़ी चुनौती क्या है?',
      'q9_a': 'शांत रहना और तनाव से बचना।',
      'q9_b': 'सामान्य उतार-चढ़ाव से निराश न होना।',
      'q9_c': 'समय बर्बाद किए बिना दवाओं और स्टॉक को याद रखना।',
      'q9_d': 'शुरुआत से मधुमेह के बारे में सब कुछ सीखना।',
      'q10': '10. आप कितने समय से मधुमेह का प्रबंधन कर रहे हैं?',
      'q10_a': 'हाल ही में निदान हुआ है।',
      'q10_b': 'कुछ वर्षों से और मैं इसे अच्छी तरह से जानता/जानती हूँ।',
      'q10_c': 'लंबे समय से, लेकिन फिर भी आशंका बनी रहती है।',
      'q10_d': 'लंबे समय से, लेकिन कभी-कभी दिनचर्या पर गुस्सा आता है।',
    },
    'ru': {
      'startBtn': 'НАЧАТЬ',
      'welcomeMsg': 'Умная забота о вашем здоровье.',
      'welcome': 'С возвращением!',
      'subtitle': 'Войдите, чтобы получить доступ к аккаунту и поговорить с Дианой.',
      'sponsor': 'Спонсор: Eurofarma',
      'signin': 'Войти',
      'signup': 'Регистрация',
      'userPlaceholder': 'Эл. почта',
      'namePlaceholder': 'Полное имя',
      'passPlaceholder': 'Пароль',
      'newHere': 'Впервые здесь?',
      'createAccount': 'Создать аккаунт',
      'alreadyHaveAccount': 'Уже есть аккаунт?',
      'dianaTitle': 'Диана',
      'dianaSub': 'Виртуальный ассистент здоровья Eurofarma',
      'dianaChatPlaceholder': 'Введите вопрос о режиме или уровне сахара...',
      'medReminder': 'Мои лекарства',
      'addMed': 'Добавить лекарство',
      'medName': 'Название лекарства',
      'medSchedule': 'Время (напр.: 08:00, 20:00)',
      'medStock': 'Текущий запас (ед.)',
      'medDaily': 'Дневной расход (ед.)',
      'save': 'Сохранить',
      'stockSuffix': 'дн. осталось. Пора пополнить запас!',
      'stockSafe': 'Безопасный запас более чем на',
      'days': 'дней.',
      'dianaGreeting': 'Здравствуйте! Я **Диана**, ваш ассистент здоровья Eurofarma. Как я могу помочь вам с контролем сахара сегодня?',
      'errorAuth': 'Неверный e-mail или пароль.',
      'errorEmpty': 'Пожалуйста, заполните все поля.',
      'successRegister': 'Аккаунт успешно создан! Ответьте на вопросы профиля.',
      'dianaThinking': 'Диана печатает...',
      'notifTitle': 'Разрешить уведомления?',
      'notifBody': 'GlicoCare хочет отправлять напоминания о приеме лекарств и запасах.',
      'allow': 'Разрешить',
      'deny': 'Не сейчас',
      'chip1': '🍎 Рекомендуемые продукты',
      'chip2': '💊 Совет по лекарствам',
      'chip3': '📊 Что делать при гипогликемии?',
      'profileTitle': 'Профиль пользователя',
      'close': 'Закрыть',
      'questionTitle': 'Анкета профиля',
      'q1': '1. Когда уровень сахара выходит из нормы, какова ваша первая реакция?',
      'q1_a': 'Я очень сильно волнуюсь и постоянно проверяю его.',
      'q1_b': 'Я раздражаюсь и хочу все забросить.',
      'q1_c': 'Я отношусь к этому объективно и следую плану.',
      'q1_d': 'Я чувствую себя растерянно и не знаю, что делать.',
      'q2': '2. Как вы предпочитаете справляться со стрессом или трудностями?',
      'q2_a': 'Мне нужна поддержка и спокойный разговор.',
      'q2_b': 'Я ищу конкретные данные и прямые объяснения.',
      'q2_c': 'Я предпочитаю легкость, чтобы снять напряжение.',
      'q2_d': 'Мне нужны пошаговые инструкции.',
      'q3': '3. Какой тон общения вам нравится меньше всего?',
      'q3_a': 'Нравоучительный или строгий тон.',
      'q3_b': 'Долгие речи без конкретики.',
      'q3_c': 'Отсутствие эмпатии или холодность.',
      'q3_d': 'Слишком сложные или непонятные термины.',
      'q4': '4. Как бы вы хотели, чтобы Диана общалась с вами?',
      'q4_a': 'Приветливо и спокойно (с акцентом на успокоение).',
      'q4_b': 'Прямо и объективно (с акцентом на данные и факты).',
      'q4_c': 'Вдохновляюще и легко (с акцентом на мотивацию).',
      'q4_d': 'Обучающе и подробно (терпеливо объясняя базовые вещи).',
      'q5': '5. Каким напоминаниям вы отдаете предпочтение?',
      'q5_a': 'Мягким и заботливым уведомлениям.',
      'q5_b': 'Коротким и прямым напоминаниям.',
      'q5_c': 'Уведомлениям с элементами поддержки.',
      'q5_d': 'Разъяснительным напоминаниям о причине приема.',
      'q6': '6. Каков темп вашей повседневной жизни?',
      'q6_a': 'Очень суетливый, вызывает тревогу.',
      'q6_b': 'Структурированный и хорошо спланированный.',
      'q6_c': 'Немного непредсказуемый и насыщенный.',
      'q6_d': 'Я все еще пытаюсь организовать свой режим.',
      'q7': '7. Как вы обычно питаетесь?',
      'q7_a': 'Я дисциплинированно следую своему плану.',
      'q7_b': 'Из-за тревоги я часто заедаю стресс.',
      'q7_c': 'Иногда меня расстраивают ограничения в диете.',
      'q7_d': 'Я пока плохо разбираюсь в подсчете углеводов.',
      'q8': '8. Каков ваш уровень физической активности?',
      'q8_a': 'Я регулярно занимаюсь спортом.',
      'q8_b': 'Мне трудно поддерживать регулярность из-за стресса.',
      'q8_c': 'Считаю это скучным, но делаю при возможности.',
      'q8_d': 'Я только начинаю.',
      'q9': '9. Какова ваша главная проблема со здоровьем на данный момент?',
      'q9_a': 'Сохранять спокойствие и избегать стресса.',
      'q9_b': 'Не расстраиваться из-за нормальных колебаний сахара.',
      'q9_c': 'Помнить о лекарствах и запасах без лишних трат времени.',
      'q9_d': 'Узнать все о диабете с нуля.',
      'q10': '10. Как долго вы контролируете диабет?',
      'q10_a': 'Диагноз поставлен недавно.',
      'q10_b': 'Уже несколько лет, я хорошо во всем разбираюсь.',
      'q10_c': 'Долгое время, но все еще испытываю опасения.',
      'q10_d': 'Долгое время, но бывают дни раздражения на рутину.',
    },
  };
}